# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f416b360a3828ccb0d9f7f1915304fbca5023bbd1240630727a95aadca9a8b2a9fce6222e433654cf364b0e0f812a12edb9037c40a6643521a8db589c9618291

test:
  secret_key_base: f4120bd484377eb51f5f94e7723b729567c15724004587d60af1af20bb710d4a2d23105d1a03e1aaccce5e0756a9d6196f11555db9d7dd632b7b1ce5ae60d147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
