# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4ab5f30d16611fd6ef16a148ffd42766e3b085d4b799c44ef201903d049792ec92be129edc0a7d97b2282d1c1c6ab137140220decc17ae5ce2eb8a174e43f14

test:
  secret_key_base: 75f7830fd7a156c6136c062cf004c864cf26b62ccdf660c0e64c3e42a2f5c693b4f8c5d96ec33882df704a288ad8a1a87e7293b974a9bb5b32cfebb34b6aaff7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
