# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64c33fbaa023f8cc6a29fd05dce6ec2f226f1d16ac4064c6775b87427de005c3504d19291944aff9fec78b0dfc72b30c0ed06247f6f026d71bcb8b0542a54216

test:
  secret_key_base: feabee4d18bf100832ab7eae28bc51cd9e8db841ccc26904a015d933bb3af868d45f5bffb5634a5997d406b7f2d2a5c0bca32aa1abf8894864c0ad67190ee016

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
