# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c523d846386dfab7c71d02b18db23ecbadd939e3ac487ac0f574c3d693bcb4ed7dad34d7c532fb3966cbbb64096d27b9d727427b7f6f10c1dd96cd2e30088bb

test:
  secret_key_base: 0cf3031286f7a61d46a518f795a1f7bfa15e53b5d671513495b675a3aa4c60f0b278d5c406850d5901733896797004cb4069ade7291bf6f26e2a97cb240f2cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
